
import Layout from '../components/front/Layout'




export default function Home() {
  return (<>
 

      <Layout title="asdasdasd" >

          <h1 className='text-danger' >body</h1>

      </Layout>

    </> )
}









{/* <div className={styles.container}>
<Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>


<footer className={styles.footer}>
  <a
    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    target="_blank"
    rel="noopener noreferrer"
  >
    Powered by{' '}
    <span className={styles.logo}>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </span>
  </a>
</footer>
</div> */}